# Generated by Django 4.2.28 on 2026-02-21 06:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'Category name cannot exceed 50 characters.', 'unique': 'This category already exists.'}, help_text='Enter the name of the dessert category (e.g. Cakes, Cookies).', max_length=50, unique=True, verbose_name='Category Name')),
                ('description', models.TextField(blank=True, help_text='Optional: short description of this category.', null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the ingredient name.', max_length=50, verbose_name='Ingredient Name')),
                ('is_allergen', models.BooleanField(default=False, help_text='Mark if this ingredient is a known allergen.', verbose_name='Contains Allergen')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Dessert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'max_length': 'Dessert name cannot exceed 100 characters.'}, help_text='Enter the name of the dessert.', max_length=100, verbose_name='Dessert Name')),
                ('description', models.TextField(help_text='Describe the dessert in detail.', verbose_name='Description')),
                ('price', models.DecimalField(decimal_places=2, error_messages={'min_value': 'Price must be greater than zero.'}, help_text='Enter the price in EUR.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price')),
                ('image', models.ImageField(blank=True, help_text='Upload an image of the dessert (optional).', null=True, upload_to='desserts/', verbose_name='Image')),
                ('is_available', models.BooleanField(default=True, help_text='Uncheck if this dessert is currently unavailable.', verbose_name='Available')),
                ('category', models.ForeignKey(help_text='Select the category for this dessert.', on_delete=django.db.models.deletion.CASCADE, related_name='desserts', to='desserts.category', verbose_name='Category')),
                ('ingredients', models.ManyToManyField(blank=True, help_text='Select the ingredients used in this dessert.', related_name='desserts', to='desserts.ingredient', verbose_name='Ingredients')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
