# Generated by Django 4.2.28 on 2026-02-18 17:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='dessert',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='ingredient',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, help_text='Optional: short description of this category.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Category name cannot exceed 50 characters.', 'unique': 'This category already exists.'}, help_text='Enter the name of the dessert category (e.g. Cakes, Cookies).', max_length=50, unique=True, verbose_name='Category Name'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='category',
            field=models.ForeignKey(help_text='Select the category for this dessert.', on_delete=django.db.models.deletion.CASCADE, related_name='desserts', to='desserts.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='description',
            field=models.TextField(help_text='Describe the dessert in detail.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the dessert (optional).', null=True, upload_to='desserts/', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='ingredients',
            field=models.ManyToManyField(blank=True, help_text='Select the ingredients used in this dessert.', related_name='desserts', to='desserts.ingredient', verbose_name='Ingredients'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Uncheck if this dessert is currently unavailable.', verbose_name='Available'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Dessert name cannot exceed 100 characters.'}, help_text='Enter the name of the dessert.', max_length=100, verbose_name='Dessert Name'),
        ),
        migrations.AlterField(
            model_name='dessert',
            name='price',
            field=models.DecimalField(decimal_places=2, error_messages={'min_value': 'Price must be greater than zero.'}, help_text='Enter the price in EUR.', max_digits=6, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='is_allergen',
            field=models.BooleanField(default=False, help_text='Mark if this ingredient is a known allergen.', verbose_name='Contains Allergen'),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Enter the ingredient name.', max_length=50, verbose_name='Ingredient Name'),
        ),
    ]
